const date = new Date();
const day = String(date.getDate()).padStart(2 , '0');
const month = String(date.getMonth()+1).padStart(2 , '0');
const year = String(date.getFullYear());
const currentYear = day + "-" + month + "-" + year;
const currentYear2 = day + "/" + month + "/" + year;
const currentYear3 = month + "-" + day + "-" + year;
const currentYear4 = month + "/" + day + "/" + year;
console.log(currentYear);
console.log(currentYear2);
console.log(currentYear3);
console.log(currentYear4);